GET http://localhost:3000/blogs

###

GET http://localhost:3000/blogs/63ad869abc2f2fafb5b5362d

###

POST http://localhost:3000/blogs
Content-Type: application/json

{
    "title":"Fucking Amazing",
    "content": "TY webdev TY webdev simpTY webdev simpTY webdev simpTY webdev simp"
}

###

DELETE http://localhost:3000/blogs/63ae4c3c7d3090365b52b83b

###

PATCH http://localhost:3000/blogs/63ae4c7a7d3090365b52b849
Content-Type: application/json

{
    "title": "2n Blog",
    "content": "New ???",
    
    "time":""
}

###

PATCH http://localhost:3000/blogs/63ae4c987d3090365b52b851/newComment
Content-Type: application/json

{
        "commentEmail": "new Comment wtf",
        "commentTime": "time",
        "commentContent": "fuck this shit"
}